CREATE TABLE t_tarefa(
     CD_TAREFA            VARCHAR(30)  NOT NULL PRIMARY KEY
    ,NM_TAREFA            VARCHAR(60) NOT NULL
    ,TP_TAREFA            VARCHAR(1) NOT NULL
    ,CD_UNIDADE           INTEGER  NOT NULL
    ,IN_EXCLUSAO          VARCHAR(1) NOT NULL
    ,DT_INSERT            VARCHAR(19) NOT NULL
    ,NM_USER_INSERT       VARCHAR(14) NOT NULL
    ,DT_UPDATE            VARCHAR(19) NOT NULL
    ,NM_USER_UPDATE       VARCHAR(13) NOT NULL
    ,ST_BATERIA           VARCHAR(1)
    ,IN_CONCORRENTE       VARCHAR(1)
    ,TP_INCORPORACAO      VARCHAR(30)
    ,CD_FORNECEDOR        VARCHAR(6)
    ,NR_PUB               VARCHAR(22)
    ,CD_SISTEMA           VARCHAR(30)
    ,CD_FADT              VARCHAR(30)
    ,CD_WUC               VARCHAR(30)
    ,CD_SISTEMA_WUC       VARCHAR(30)
    ,CD_MODELO            INTEGER
    ,QT_DURACAO           INTEGER  NOT NULL
    ,CD_MATERIAL          VARCHAR(30)  NOT NULL
    ,NR_CARTAO            VARCHAR(6) NOT NULL
    ,DT_CARTAO            VARCHAR(20)
    ,NR_ITEM_CARTAO       VARCHAR(30)
    ,NR_REVISAO           VARCHAR(30)
    ,NR_SECAO             VARCHAR(30)
    ,CD_SECAO_ATA         VARCHAR(30)
    ,CD_CAPITULO_ATA      VARCHAR(30)
    ,CD_ARTIGO_ATA        VARCHAR(30)
    ,CD_FUNCAO_ATA        VARCHAR(30)
    ,CD_IDENTIFICADOR_ATA VARCHAR(30)
    ,CD_DIFERENCIADOR_ATA VARCHAR(30)
    ,CD_SUBTAREFA_ATA     VARCHAR(30)
    ,CD_TYPE              VARCHAR(3)
    ,DS_ZONA              VARCHAR(30)
    ,CD_CATEGORIA_TAREFA  VARCHAR(30)
    ,DS_AREA              VARCHAR(30)
    ,CD_NIVEL             VARCHAR(1) NOT NULL
    ,NR_ASSESSORAMENTO    VARCHAR(30)
    ,CD_ATC               VARCHAR(30)
    ,CD_AREA              VARCHAR(30)
    ,CD_ZONA              VARCHAR(30)
    ,CD_TAREFA_PAI        VARCHAR(30)
    ,CD_MATERIAL_REMINST  VARCHAR(30)
    ,CD_POSICAO           VARCHAR(30)
    ,QT_RECURSOS          INTEGER
    ,QT_HH                INTEGER
    ,CD_MATERIAL_CJM      VARCHAR(30)
    ,CD_PROJETO           VARCHAR(2)
    ,CD_FUNCAO            VARCHAR(3) NOT NULL
    ,NR_CAPITULO_SECAO    VARCHAR(30)
    ,TX_OBS               VARCHAR(760)
    ,DS_TAREFA            VARCHAR(30)
    ,IN_PTN               VARCHAR(30)
    ,CD_UNIDADE_EXECUTORA VARCHAR(30)
    ,CD_SETOR_EXECUTORA   VARCHAR(30)
    ,NR_FICHA             INTEGER
    ,CD_PERIODICIDADE     VARCHAR(2) NOT NULL
    ,ID_BOLETIM           INTEGER
    ,QT_HR_PARADA         INTEGER
    ,IN_FECHA_BOLETIM     VARCHAR(1) NOT NULL
    ,TP_FORMA_ATUACAO     VARCHAR(1)
    ,CD_MODELO_LOCAL      INTEGER
    ,ID_RESP_PREVENTIVA   INTEGER
    ,FOREIGN KEY (CD_PROJETO) REFERENCES t_projeto(CD_PROJETO)
);