CREATE TABLE T_PROJETO(
                          CD_PROJETO           VARCHAR(2) NOT NULL PRIMARY KEY,
                          DT_INSERT            VARCHAR(19),
                          NM_USER_INSERT       VARCHAR(14),
                          DT_UPDATE            VARCHAR(19) NOT NULL,
                          NM_USER_UPDATE       VARCHAR(6) NOT NULL,
                          SG_PROJETO           VARCHAR(8) NOT NULL,
                          CD_UNIDADE           VARCHAR(3) NOT NULL,
                          CD_DAO               VARCHAR(3),
                          DS_PROJETO           VARCHAR(49) NOT NULL,
                          CD_OM_GDE_CMDO       INTEGER,
                          IN_COMBLUB           VARCHAR(1),
                          TP_PROJETO           VARCHAR(1) NOT NULL,
                          TP_PERFIL            VARCHAR(1) NOT NULL,
                          DT_IMPLANTACAO       VARCHAR(19) NOT NULL,
                          TX_PROJETO           VARCHAR(464),
                          TP_AREA_STA          VARCHAR(1),
                          IN_GERAL_STA         VARCHAR(1),
                          CD_ATIVIDADE_CUSTO   BIT,
                          CD_CENTRO_CUSTO      INTEGER,
                          CD_SUBCENTRO_CUSTO   INTEGER,
                          IN_ATIVO             VARCHAR(1) NOT NULL,
                          TP_DEPURACAO_PROJETO VARCHAR(1),
                          DT_FIM_INDICADOR     VARCHAR(50),
                          IN_PROJETO_MAPA      VARCHAR(1) NOT NULL,
                          IN_SISTEMA_EXTERNO   VARCHAR(1) NOT NULL,
                          DS_PROJETO_INGLES    VARCHAR(49) NOT NULL
);